### ISSUE TITLE
Web API

### ISSUE THREAD

**Issue by KarmaDeb** [FriendsOfFlarum/upload#294] opened 2021-08-21 23:52 UTC
We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thank you for your ongong support, patience, and cooperation!

* Flarum Community Discussion: https://discuss.flarum.org/d/16242
* Discord Server: https://friendsofflarum.org/discord
* Twitter: https://twitter.com/FriendsOfFlarum

Hi, I was wondering if there's a web API for this extension to search a resource download url by name

**Comment by DavideIadeluca** [comment] 2024-06-22 15:46
Hi @KarmaDeb, no, there is currently no API to search for resources by name. 

As this issue is a duplicate of https://github.com/FriendsOfFlarum/upload/issues/279, it will be closed.

**Closed by DavideIadeluca** 2024-06-22 15:46 UTC
Labels: enhancement
