### ISSUE TITLE
Clickable images

### ISSUE THREAD

**Issue by XakepSDK** [FriendsOfFlarum/upload#147] opened 2018-07-04 17:01 UTC
Make images clickable to open in full size.

**Comment by DavideIadeluca** [comment] 2024-06-22 13:57
Duplicate of https://github.com/FriendsOfFlarum/upload/issues/46.  I can recommend https://github.com/iamdarkle/fancybox for anyone still interested in this.

**Closed** 2024-06-22 13:57 UTC
