### ISSUE TITLE
Not compatible with French Language 

### ISSUE THREAD

**Issue by KazeroG** [FriendsOfFlarum/upload#136] opened 2018-04-30 20:52 UTC
- flagrow/upload extension version: 0.6.0
- flarum version: Flarum core 0.1.0-beta.7
- upload adapter causing issues: ![img](https://box.everhelper.me/attachment/1688924/7xro1ed9tx4apy6313rt/1052277-5aKolLRBZJ116MsL/screen.jpeg)
- Loaded extensions: Core, date, libxml, openssl, pcre, sqlite3, zlib, bz2, calendar, ctype, curl, hash, filter, ftp, gettext, gmp, SPL, iconv, pcntl, readline, Reflection, session, standard, shmop, SimpleXML, mbstring, tokenizer, xml, bcmath, dom, fileinfo, gd, imagick, imap, intl, Phar, json, exif, mcrypt, mysqlnd, mysqli, PDO, pdo_mysql, pdo_sqlite, posix, pspell, soap, sockets, tidy, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, phalcon, ionCube Loader
EXT flarum-approval v0.1.0-beta.7
EXT flarum-bbcode v0.1.0-beta.5
EXT oe800-bbcode-cards 0.1.4
EXT flarum-emoji v0.1.0-beta.6
EXT flarum-english v0.1.0-beta.7
EXT flarum-flags v0.1.0-beta.7
EXT milescellar-french v1.1.0
EXT flarum-likes v0.1.0-beta.6
EXT flarum-lock v0.1.0-beta.7
EXT flarum-markdown v0.1.0-beta.5
EXT flarum-mentions v0.1.0-beta.7
EXT reflar-polls 1.1.0
EXT flarum-sticky v0.1.0-beta.7
EXT flarum-subscriptions v0.1.0-beta.6
EXT flarum-suspend v0.1.0-beta.7
EXT flarum-tags v0.1.0-beta.8

---

Not compatible with French Language https://discuss.flarum.org/d/615-french-language-pack

**Comment by clarkwinkelmann** [comment] 2018-06-29 18:13
It looks like we completely forgot to respond to this, sorry.

It's not a bug, it's just the French translation being horribly out of date with many missing texts... Probably not the only translation that hasn't been kept up to date.

If you're interested in helping translating the missing strings, you can compare the latest `en.yml` with `fr.yml` and translate+add the missing keys in French. There might also be dead translation keys no longer used that can be removed.

I don't have the time to update the language pack myself in the foreseeable future :sweat_smile:

**Comment by clarkwinkelmann** [comment] 2020-02-06 23:22
All languages have been removed now that FriendsOfFlarum took over the extension. These kind of issues are now the responsibility of language pack maintainers. I'm closing the issue.

**Closed by clarkwinkelmann** 2020-02-06 23:22 UTC
Labels: enhancement
