### ISSUE TITLE
Admin panel is broken since 0.8.0

### ISSUE THREAD

**Issue by imorland** [FriendsOfFlarum/upload#195] opened 2020-02-09 14:23 UTC
Looks like a small error in the console in /admin after the extension is enabled

`Uncaught TypeError: Cannot read property 'settings' of undefined`

This causes further extension tabs not not load

**Comment by luceos** [comment] 2020-02-14 10:40
I noticed upload was broken too. I think we need to solve this ASAP.

**Comment by luceos** [comment] 2020-02-14 11:07
@imorland what php version do you run? Can you output `php flarum info` perhaps?

**Comment by imorland** [comment] 2020-02-14 11:12
@luceos this is on our [preview site](https://preview.community.giffgaff.com/)

```
root@community-flarum-apache-preview-microservice-base-f5ff9fd5pqdxg:/var/www# php flarum info
Flarum core 0.1.0-beta.11.1
PHP version: 7.2.22
Loaded extensions: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, readline, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apcu, bcmath, calendar, exif, gd, geoip, gettext, gmp, intl, ldap, memcached, mysqli, pcntl, pdo_mysql, redis, sodium, sysvmsg, tidy, timezonedb, xsl, zip, Zend OPcache
+---------------------------------+-----------------+------------------------------------------+
| Flarum Extensions               |                 |                                          |
+---------------------------------+-----------------+------------------------------------------+
| ID                              | Version         | Commit                                   |
+---------------------------------+-----------------+------------------------------------------+
| flarum-tags                     | v0.1.0-beta.11  |                                          |
| giffgaff-giffgaff-community-sso | 0.1.1           | 0ccc765231597712314e26900502cace049d99c8 |
| flarum-lang-english             | v0.1.0-beta.11  |                                          |
| flarum-approval                 | v0.1.0-beta.8   |                                          |
| flarum-bbcode                   | v0.1.0-beta.8   |                                          |
| michaelbelgium-discussion-views | v0.1.0-beta.8.3 |                                          |
| flarum-emoji                    | v0.1.0-beta.10  |                                          |
| fof-default-user-preferences    | 0.2.0           |                                          |
| fof-formatting                  | 0.1.4           |                                          |
| fof-profile-image-crop          | 0.1.1           |                                          |
| fof-user-bio                    | 0.1.3           |                                          |
| flarum-lock                     | dev-master      |                                          |
| flarum-markdown                 | v0.1.0-beta.10  |                                          |
| flarum-mentions                 | v0.1.0-beta.10  |                                          |
| fof-reactions                   | 0.2.1           |                                          |
| flarum-sticky                   | dev-master      |                                          |
| flarum-subscriptions            | dev-master      |                                          |
| giffgaff-spoilers               | 0.1.1           | 379a3ff332f9494677bab2a224397ddd6d9e5083 |
| fof-follow-tags                 | 0.3.4           |                                          |
| fof-polls                       | 0.1.1           |                                          |
| clarkwinkelmann-circle-groups   | 0.2.1           |                                          |
| fof-upload                      | 0.8.0           |                                          |
| flagrow-impersonate             | 0.3.0           |                                          |
| fof-ignore-users                | 0.1.5           |                                          |
| v17development-seo              | 1.1             |                                          |
| fof-links                       | 0.2.1           |                                          |
| giffgaff-gdpr-rtbf              | 0.1.0           | aeb17e4c34ad70021febb0aaaf5a39cbbaf794d1 |
| giffgaff-user-manager           | 0.1.6           | 1d6e2eeeea5d375aea6243d42f12937aca9fcd14 |
| giffgaff-post-decontaminator    | 0.1.0           | 86b4d142de6a2fb8efd51b38fa897b4871e9ea27 |
| giffgaff-drafts                 | 0.1.4           |                                          |
| flarum-flags                    | v0.1.0-beta.9   |                                          |
| giffgaff-post-image-blocker     | 0.1.0           | c3502030ecd0a6a49ca79642e16dbecd4e278625 |
| giffgaff-default-avatar         | 0.1.3           | 184dd0fe5c3844737ec750f0f709cf395e129b57 |
| fof-byobu                       | 0.3.5.2         |                                          |
| flagrow-analytics               | 0.10.0          |                                          |
| bokt-redis                      | 0.1.0           |                                          |
| giffgaff-theme-admin-main       | 0.1.0           | b0e2aac8c81bbeaf6ad06c05655c099f9ab151d1 |
| imorland-nightmode              | 0.4.1           |                                          |
| franzl-open-links-in-new-tab    | v0.1.0          |                                          |
| giffgaff-ban-user-by-id         | 0.1.12          | a5d398c0a66b7a6c3307238118acbb75dc756ad1 |
| giffgaff-ip-banning             | 0.1.8           | 4467641beb7090831b70241c018247e8f9f43f6f |
| fof-split                       | 0.4.3           |                                          |
| giffgaff-post-id-redirector     | 0.1.0           | 21cbcf2c3555dce88d55dd5fb47b09134b67f0f4 |
| fof-best-answer                 | 0.1.5           |                                          |
| giffgaff-theme-forum-main       | 0.1.6           | 45afedead10b31717a42947f3b53d83512d7e0f3 |
| giffgaff-theme-thumbnail        | 0.1.7           | a05f58ea2100877f1c561ace86499e51c165ee66 |
| giffgaff-mail-templates         | dev-master      | 3a35c0dc8bc8f418b50319c5015be9b0f68f9a5c |
+---------------------------------+-----------------+------------------------------------------+
Base URL: https://preview.community.giffgaff.com
Installation path: /var/www
Debug mode: off
root@community-flarum-apache-preview-microservice-base-f5ff9fd5pqdxg:/var/www#
```

**Comment by luceos** [comment] 2020-02-14 11:14
I can't reproduce locally using PHP 7.3.11. This was the error I received in a new clean install with 0.8.0 of upload:

Flarum encountered a boot error (ReflectionException)
Class GuzzleHttp\Client does not exist
thrown in /home/forge/veteranclan.com/vendor/illuminate/container/Container.php on line 838

**Comment by imorland** [comment] 2020-02-14 11:15
Yea, the solution to that one, for us at least, was to `composer require guzzlehttp/guzzle`

**Comment by imorland** [comment] 2020-02-14 11:16
Worth noting that for our case, it was an upgrade from 0.7.0 to 0.8.0, if that makes any difference

**Comment by luceos** [comment] 2020-02-14 11:22
Are you able to trace your issue with the settings on null? My assumption is that the js still uses the wrong key for settings (flagrow vs fof).

**Comment by imorland** [comment] 2020-02-14 11:52
Looks like it's an issue our end, rather than with 0.8.0

Disabling `giffgaff-user-manager` appears to resolve the issue. I'll do some further investigation later on

**Comment by imorland** [comment] 2020-02-14 11:53
However that doesn't explain why you had the error?

**Comment by luceos** [comment] 2020-02-25 14:46
I have no idea, let's close this until we get it again.

**Closed by luceos** 2020-02-25 14:46 UTC
Labels: bug
